const iconlist2 = ["hl-icon-laiyuan"
    ,"hl-icon-nanguo"
    ,"hl-icon-wupinglun"
    ,"hl-icon-wushuju"
    ,"hl-icon-jiantoushou"
    ,"hl-icon-jiantouwei"
    ,"hl-icon-biaoqian"
    ,"hl-icon-biaoqian-fill"
    ,"hl-icon-fasong"
    ,"hl-icon-lianjie"
    ,"hl-icon-dianshiju3"
    ,"hl-icon-dianshiju3-fill"
    ,"hl-icon-jiangzhang"
    ,"hl-icon-jiangzhang-fill"
    ,"hl-icon-jiantoushang-fill"
    ,"hl-icon-jiantouxia-fill"
    ,"hl-icon-jiaose"
    ,"hl-icon-jiaose-fill"
    ,"hl-icon-huo"
    ,"hl-icon-huo-fill"
    ,"hl-icon-hua"
    ,"hl-icon-hua-fill"
    ,"hl-icon-gaoxiao"
    ,"hl-icon-gaoxiao-fill"
    ,"hl-icon-gouwu"
    ,"hl-icon-gouwu-fill"
    ,"hl-icon-shouye"
    ,"hl-icon-shouye-fill"
    ,"hl-icon-rili"
    ,"hl-icon-rili-fill"
    ,"hl-icon-paihang"
    ,"hl-icon-paihang-fill"
    ,"hl-icon-mingxing"
    ,"hl-icon-mingxing-fill"
    ,"hl-icon-dianying"
    ,"hl-icon-dianying-fill"
    ,"hl-icon-dianshiju"
    ,"hl-icon-dianshiju-fill"
    ,"hl-icon-dianshiju2"
    ,"hl-icon-dianshiju2-fill"
    ,"hl-icon-zongyi"
    ,"hl-icon-zongyi-fill"
    ,"hl-icon-zhibo"
    ,"hl-icon-zhibo-fill"
    ,"hl-icon-dongman"
    ,"hl-icon-dongman-fill"
    ,"hl-icon-shexiangji"
    ,"hl-icon-shexiangji-fill"
    ,"hl-icon-zuichun"
    ,"hl-icon-zuichun-fill"
    ,"hl-icon-zhuanti"
    ,"hl-icon-zhuanti-fill"
    ,"hl-icon-youxi"
    ,"hl-icon-youxi-fill"
    ,"hl-icon-yinyue"
    ,"hl-icon-yinyue-fill"
    ,"hl-icon-xinwen"
    ,"hl-icon-xinwen-fill"
    ,"hl-icon-zuixin"
    ,"hl-icon-zuixin-fill"
    ,"hl-icon-shu"
    ,"hl-icon-shu-fill"
    ,"hl-icon-zuanshi"
    ,"hl-icon-zuanshi-fill"
    ,"hl-icon-vip"
    ,"hl-icon-vip-fill"
    ,"hl-icon-tixing"
    ,"hl-icon-tixing-fill"
    ,"hl-icon-shipinku"
    ,"hl-icon-shipinku-fill"
    ,"hl-icon-shipin"
    ,"hl-icon-shipin-fill"
    ,"hl-icon-huiyuan"
    ,"hl-icon-huiyuan-fill"
    ,"hl-icon-bofang"
    ,"hl-icon-bofang-fill"
    ,"hl-icon-weixin"
    ,"hl-icon-weixin-fill"
    ,"hl-icon-qq"
    ,"hl-icon-qq-fill"
    ,"hl-icon-pinglun"
    ,"hl-icon-pinglun-fill"
    ,"hl-icon-liuyan"
    ,"hl-icon-liuyan-fill"
    ,"hl-icon-xihuan"
    ,"hl-icon-xihuan-fill"
    ,"hl-icon-xingxing"
    ,"hl-icon-xingxing-fill"
    ,"hl-icon-zanshang"
    ,"hl-icon-zanshang-fill"
    ,"hl-icon-zanxia"
    ,"hl-icon-zanxia-fill"
    ,"hl-icon-fenxiang"
    ,"hl-icon-fenxiang2"
    ,"hl-icon-shouji"
    ,"hl-icon-shoucang"
    ,"hl-icon-shezhi"
    ,"hl-icon-shijian"
    ,"hl-icon-jifenjilu"
    ,"hl-icon-jifen"
    ,"hl-icon-jilu"
    ,"hl-icon-jubao"
    ,"hl-icon-lajitong"
    ,"hl-icon-lihe"
    ,"hl-icon-hongbao"
    ,"hl-icon-erweima"
    ,"hl-icon-chongzhi"
    ,"hl-icon-chongzhijilu"
    ,"hl-icon-tixian"
    ,"hl-icon-bianji"
    ,"hl-icon-appxz"
    ,"hl-icon-biaoqing"
    ,"hl-icon-tuichu"
    ,"hl-icon-tuijian"
    ,"hl-icon-tongzhi"
    ,"hl-icon-xiazai"
    ,"hl-icon-xie"
    ,"hl-icon-yifu"
    ,"hl-icon-yueliang"
    ,"hl-icon-taiyang"
    ,"hl-icon-caidan"
    ,"hl-icon-zhengxu"
    ,"hl-icon-daoxu"
    ,"hl-icon-sousuo"
    ,"hl-icon-shaixuan"
    ,"hl-icon-shuaxin"
    ,"hl-icon-qiehuan"
    ,"hl-icon-xiayiji"
    ,"hl-icon-shangyiji"
    ,"hl-icon-dui"
    ,"hl-icon-cuo"
    ,"hl-icon-jia"
    ,"hl-icon-jiantouxia"
    ,"hl-icon-jiantouyou"
    ,"hl-icon-jiantoushang"
    ,"hl-icon-jiantouzu"] 
const iconlist = ["icon-yingyong"
    ,"icon-tijiao"
    ,"icon-biaoqing4"
    ,"icon-liebiao"
    ,"icon-daoxu"
    ,"icon-yueliang"
    ,"icon-bairi"
    ,"icon-lishi"
    ,"icon-weixin"
    ,"icon-qianbi1"
    ,"icon-shouqi"
    ,"icon-QR"
    ,"icon-xingqiu"
    ,"icon-zhankaixiajiantou-"
    ,"icon-right-line"
    ,"icon-tianchongxing-"
    ,"icon-sousuo"
    ,"icon-fenxiang"
    ,"icon-zhuti"
    ,"icon-shoucang"
    ,"icon-app"
    ,"icon-dashang"
    ,"icon-zimu"
    ,"icon-liuyan"
    ,"icon-link-fill"
    ,"icon-shuaxin"
    ,"icon-jurassic_wait"
    ,"icon-wode"
    ,"icon-youxiangicon"
    ,"icon-you-"
    ,"icon-zuo-"
    ,"icon-jifen"
    ,"icon-tanhao"
    ,"icon-xiazai"
    ,"icon-bofang"
    ,"icon-shandian"
    ,"icon-shaixuan"
    ,"icon-jifen1"
    ,"icon-jifen2"
    ,"icon-zhuye"
    ,"icon-shandian1"
    ,"icon-chakanbeifen"
    ,"icon-gouwudai"
    ,"icon-gonggao"
    ,"icon-xunzhang"
    ,"icon-guanbi"
    ,"icon-fankuixuanzhong"
    ,"icon-gouwudai1"
    ,"icon-zhuye1"
    ,"icon-rehot"
    ,"icon-remen-fill"
    ,"icon-zhengque-correct"
    ,"icon-icon_commone_shaixuanmian"
    ,"icon-wode1"
    ,"icon-shanchu"
    ,"icon-caidan"
    ,"icon-sousuo"
    ,"icon-rehot"
    ,"icon-guanbi"
    ,"icon-shandian"
    ,"icon-gouwudai1"
    ,"icon-link-fill"
    ,"icon-feedback"
    ,"icon-close"]
const IconPick = () => {
  return (
    <div style={{
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '1rem',
        backgroundColor: '#f0f0f0',
        borderRadius: '5px'
    }}>
        <h1>Icon 1</h1><br/>
        {iconlist.map((item, index) => (
            <i style={{
                fontSize: '2rem'
            }} className={"iconfont "+item+" mr-1 gradient text-transparent"} key={index}></i>
        ))}
        <h1>Icon 2</h1><br/>
        {iconlist2.map((item, index) => (
            <i style={{
                fontSize: '2rem'
            }} className={"iconfont2 "+item+" mr-1 gradient text-transparent"} key={index}></i>
        ))}
    </div>
  )
}

export default IconPick